[zh]
  title = "哇咔咔逗比遊戲實驗室 Wakaka Dubi Game Lab"
  languageName = "繁體中文"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/en"
[en]
  title = "哇咔咔逗比遊戲實驗室 Wakaka Dubi Game Lab"
  languageName = "English"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/en"

[ko]
  title = "哇咔咔逗比遊戲實驗室 Wakaka Dubi Game Lab"
  languageName = "한국어"
  weight = 3
  languagedir = "ltr"
  contentdir = "content/ko"
